### ISSUE TITLE
Multiple returns

### ISSUE THREAD

**Issue by vincentchalamon** [php-mock/php-mock-phpunit#15]
Hi,
I'm trying to create a mock of `file_get_contents` function. On the first call, it should throw an exception, but on the second call it should return a value. How can I mock it?:
```php
try {
    $content = 'data:image/jpeg;base64,'.base64_encode(file_get_contents($url));
} catch (\Exception $e) {
    $content = 'data:image/jpeg;base64,'.base64_encode(file_get_contents(realpath(__DIR__.'/path/to/my/image.png')));
}
```

**Comment by malkusch** [comment]
That's a PHPUnit question. I'll close it therefore. Please consult the PHPUnit documentation for this question.
