### ISSUE TITLE
Not working with PHPUnit 6.5

### ISSUE THREAD

**Issue by OndraM** [php-mock/php-mock-phpunit#21]
Hi, the library is not working with PHPUnit 6.5 (phpunit-mock-objects 5).

```php
<?php declare(strict_types=1);

namespace My;

use phpmock\phpunit\PHPMock;

class WillItWorkTest extends \PHPUnit\Framework\TestCase
{
    use PHPMock;

    public function testFoo(): void
    {
        $time = $this->getFunctionMock(__NAMESPACE__, 'time');
    }
}
```

Results in:
> PHP Fatal error:  Interface 'PHPUnit_Framework_MockObject_Matcher_Invocation' not found in /.../vendor/php-mock/php-mock-phpunit/classes/DefaultArgumentRemover.php on line 15

Version of relevant installed packages:
phpunit/phpunit                    6.5.1 
phpunit/phpunit-mock-objects       5.0.3  
php-mock/php-mock                  2.0.0  
php-mock/php-mock-integration      2.0.0
php-mock/php-mock-phpunit          2.0.0

May be related to https://github.com/sebastianbergmann/phpunit-mock-objects/issues/388 ?

**Comment by webimpress** [comment]
@malkusch any progress on it?

**Comment by OndraM** [comment]
Or maybe this could be part of PHPUnit 7.0 support (to be released February 2nd), so BC changes could be introduced?

**Comment by webimpress** [comment]
@OndraM Please see #27
