### ISSUE TITLE
Error: addMatcher() must implement interface PHPUnit\Framework\MockObject\Matcher\Invocation

### ISSUE THREAD

**Issue by hgezim** [php-mock/php-mock-phpunit#22]
I tried to get this to work with PHPUnit 6.4 (since 6.5 is having issues) and kept getting these errors:

There were 2 errors:

1) foo\BuiltinTest::testTime
TypeError: Argument 1 passed to PHPUnit\Framework\MockObject\InvocationMocker::addMatcher() must implement interface PHPUnit\Framework\MockObject\Matcher\Invocation, instance of phpmock\phpunit\DefaultArgumentRemover given, called in /data/wordpress/wp-content/plugins/zip-recipes/vendor/php-mock/php-mock-phpunit/classes/PHPMock.php on line 79

/data/wordpress/wp-content/plugins/zip-recipes/vendor/php-mock/php-mock-phpunit/classes/PHPMock.php:79
/data/wordpress/wp-content/plugins/zip-recipes/plugins/RecipeIndex/tests/SampleTest.php:15

**Comment by webimpress** [comment]
@hgezim can you test it please with #27 ?
