### ISSUE TITLE
PHPUnit 7 support

### ISSUE THREAD

**Issue by webimpress** [php-mock/php-mock-phpunit#25]
Any plan of adding PHPUnit 7 support? Thanks !

**Comment by mikebautista** [comment]
Yes, this would be nice! I can't upgrade to Laravel 5.6 because of the PHPUnit 7 requirement.

**Comment by mikebautista** [comment]
Yes, this would be helpful for some upgrades we're working on right now.

**Comment by ShiraNai7** [comment]
I have created a fork which supports PHPUnit 7. I couldn't solve [the problem](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/390) in a nice way (at least not easily), but it works. Feel free to use it if you really need PHPUnit 7 support *now*.

https://github.com/ShiraNai7/php-mock-phpunit

**Comment by malkusch** [comment]
Sorry guys for not acting earlier. Does any of you want to take over this project. See https://github.com/php-mock/php-mock/issues/20
