### ISSUE TITLE
phpunit 8.3: cannot implement PHPUnit\Framework\MockObject\Rule\InvocationOrder

### ISSUE THREAD

**Issue by drzraf** [php-mock/php-mock-phpunit#48]
Using PHPUnit 8.3.5, I've no such thing as `\PHPUnit\Framework\MockObject\Matcher\Invocation::class`.

As such, the following code in autoload.php
```php
if (class_exists(\PHPUnit\Framework\MockObject\Rule\InvocationOrder::class)) {
    class_alias(
        \PHPUnit\Framework\MockObject\Rule\InvocationOrder::class,
        \PHPUnit\Framework\MockObject\Matcher\Invocation::class
    );
```

causes
```
PHP Fatal error:  phpmock\phpunit\DefaultArgumentRemoverReturnTypes cannot implement PHPUnit\Framework\MockObject\Rule\InvocationOrder - it is not an interface in /vendor/php-mock/php-mock-phpunit/classes/DefaultArgumentRemoverReturnTypes.php on line 17
```

PHPUnit 8.4 seems to work though

**Comment by michalbundyra** [comment]
@drzraf thanks for reporting

As you can see all the conditions to support all possible versions of PHPUnit are very tricky there. We did not have this report before, and as you are saying if it is working with PHPUnit 8.4 there is no point to investigate that issue, imo.

It looks like just 8.5 and 9.5 are supported versions of PHPUnit so I encourage you to use one of them.

Thanks

**Comment by drzraf** [comment]
Needs to **reopen**. Under `PHPUnit 8.5.26`, I'm getting the foolowing warnings:
```
  2x: The "PHPUnit\Framework\MockObject\Rule\InvocationOrder" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "phpmock\phpunit\DefaultArgumentRemoverReturnTypes84".
    2x in blablabla

  2x: The "PHPUnit\Framework\BaseTestListener" class is considered internal. It may change without further notice. You should not use it from "phpmock\phpunit\MockDisablerPHPUnit7".
    2x in blablabla
```

The previous problem was probably a manifestation and a warning now exists to keeps developers from extending `InvocationOrder` and `BaseTestListener`
