### ISSUE TITLE
Error while mocking built-in functions like curl_init

### ISSUE THREAD

**Issue by dlevel** [php-mock/php-mock-phpunit#8]
Hi,

It is certainly a miss use of the library but I always get an error that said that the function **registerMockObject** does not exist.

I deeped into the library to find it and I didn't see any information in the README to fix this.

Thank you.

**Comment by malkusch** [comment]
Could you please give a full stack trace and a minimal code example to 
produce that situation?

Am 10.5.2016 16:17, schrieb dlevel:

**Comment by dlevel** [comment]
Here is the sample of code:

`public function testAuthenticationFailureWrongAuthorizationCode()
 {
$this->getFunctionMock(__NAMESPACE__, "curl_init");
 }
`


And the stack trace : 

`PHPUnit_Framework_Exception: PHP Fatal error:  Call to undefined method JsonRpc\Authentication\AuthTest::registerMockObject() in /var/www/api-gateway/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php on line 136
PHP Stack trace:
PHP   1. {main}() -:0
PHP   2. __phpunit_run_isolated_test() -:92
PHP   3. PHPUnit_Framework_TestCase->run() -:53
PHP   4. PHPUnit_Framework_TestResult->run() /var/www/api-gateway/vendor/phpunit/phpunit/src/Framework/TestCase.php:801
PHP   5. PHPUnit_Framework_TestCase->runBare() /var/www/api-gateway/vendor/phpunit/phpunit/src/Framework/TestResult.php:685
PHP   6. PHPUnit_Framework_TestCase->runTest() /var/www/api-gateway/vendor/phpunit/phpunit/src/Framework/TestCase.php:845
PHP   7. ReflectionMethod->invokeArgs() /var/www/api-gateway/vendor/phpunit/phpunit/src/Framework/TestCase.php:985
PHP   8. JsonRpc\Authentication\AuthTest->testAuthenticationFailureWrongAuthorizationCode() /var/www/api-gateway/vendor/phpunit/phpunit/src/Framework/TestCase.php:985
PHP   9. JsonRpc\Authentication\AuthTest->getFunctionMock() /var/www/api-gateway/module/JsonRpc/tests/Authentication/AuthTest.php:145
PHP  10. PHPUnit_Framework_MockObject_MockBuilder->getMockForAbstractClass() /var/www/api-gateway/vendor/php-mock/php-mock-phpunit/classes/PHPMock.php:79`

**Comment by dlevel** [comment]
It seems that the bug only occurs in my ide but not when I run it through the console. Maybe it is due to an auloading issue on my side.
