### ISSUE TITLE
Increase phpunit versions

### ISSUE THREAD

**Issue by jmauerhan** [php-mock/php-mock-phpunit#9]
Is there a reason this is locked to phpunit 4.0.0 || 5.0.0, and not something like `5.*` ? If there's something breaking in one of the later versions, I'd be happy to help fix it. I want to use this tool with more recent phpunit versions.

**Comment by malkusch** [comment]
> Is there a reason this is locked to phpunit 4.0.0 || 5.0.0, and not something like 5.* ?

You omitted the [caret constrain](https://getcomposer.org/doc/articles/versions.md#caret). It's locked against ^4.0.0 || ^5.0.0, not 4.0.0 || 5.0.0. 

> I want to use this tool with more recent phpunit versions.

Which particular version doesn't work for you?

**Comment by jmauerhan** [comment]
When I originally tried to use it with phpunit 5.4, I got a version constraint error. Something else I changed must have fixed it, because now it's working...

However, when I was looking into if it would work, I noticed your travis isn't building with 5.4, so that could be added :) Thanks for the time!

**Comment by malkusch** [comment]
> However, when I was looking into if it would work, I noticed your travis isn't building with 5.4, so that could be added 

Done in https://github.com/php-mock/php-mock-phpunit/commit/e47b67bfbc7c29fa61e23cc394b96e008d2904b5. Thank you
